server:
  port: 8000
spring:
  application:
    name: SCW-PROJECT
  datasource:
    url: jdbc:mysql://localhost:3306/scwdb511?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.188.146
    port: 6379
    password: offcn123
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: qyzc20200924.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GDoGiCN9TagCsMAFHNY
  accessKeySecret: a3X4NiX2aDHcD0Yzn6rW4SUFTWn3NJ
  bucketName: qyzc20200924
